export const dashboard = <i class="fa-solid fa-house fa-shake"></i>;
export const transactions = <i className="fa-solid fa-credit-card"></i>;
export const categories = <i className="fa-solid fa-tags"></i>;
export const account = <i className="fa-solid fa-wallet"></i>;
export const settings = <i className="fa-solid fa-cog"></i>;
export const out = <i class="fa-solid fa-arrow-right-from-bracket"></i>;
export const trend = <i class="fa-solid fa-chart-line-up"></i>
export const expenses = <i class="fa-solid fa-square-up"></i>;
export const money = <i class="fa-solid fa-money-simple-from-bracket"></i>;
export const freelance = <i className="fa-solid fa-earth-americas"></i>;
export const stocks = <i className="fa-solid fa-arrow-trend-up"></i>;
export const bitcoin = <i className="fa-brands fa-bitcoin"></i>;
export const piggy = <i className="fa-solid fa-piggy-bank"></i>;
export const yt = <i className="fa-brands fa-youtube"></i>;
export const card = <i className="fa-brands fa-cc-visa"></i>;
export const users = <i class="fa-regular fa-user"></i>;
export const dollar = <i className="fa-solid fa-dollar-sign"></i>;
export const calender = <i className="fa-solid fa-calendar"></i>;
export const comment = <i className="fa-solid fa-comment"></i>;
export const plus = <i class="fa-solid fa-square-plus fa-shake"></i>;
export const trash = <i className="fa-solid fa-trash"></i>;
export const signout = <i className="fa-solid fa-right-from-bracket"></i>;
export const takeaway = <i className="fa-solid fa-utensils"></i>;
export const clothing = <i className="fa-solid fa-shirt"></i>;
export const book = <i className="fa-solid fa-book-open"></i>;
export const food = <i className="fa-solid fa-bowl-food"></i>;
export const medical = <i className="fa-solid fa-briefcase-medical"></i>;
export const tv = <i className="fa-solid fa-tv"></i>;
export const circle = <i className="fa-solid fa-circle-dot"></i>;
export const rupee = <i className="fa-sharp fa-solid fa-indian-rupee-sign"></i>;
